### ISSUE TITLE
Mobile friendly touch option

### ISSUE THREAD

**Issue by yarnball** [davefp/handsome#13]
Hi,

Great work on this!

This needs to be more mobile friendly. It isn't possible to use or scroll on mobile.

Would it be possible for it to detect that when the screen is touch- it required a double tap to move? 

Keep up the good work

**Comment by davefp** [comment]
Hi! Can you be more specific about what you mean by "It isn't possible to use or scroll on mobile", and tell me what phone/browser combo you're using?

The little testing I've done on my own phone works OK. The example dashboard isn't optimized for phone screens size-wise but I can scroll around the page just fine (Chrome on Android).

**Comment by yarnball** [comment]
Hi Dave,

I've tested it on iPhones (both safari & chrome). Here's an example video- https://drive.google.com/file/d/0B2vIKj9LKu2vdDJoanFNS1BrcGc/view?usp=sharing

**Comment by davefp** [comment]
Thanks! I'll check it out.

**Comment by davefp** [comment]
@yarnball That's actually [Dashing](http://dashing.io/) in your video, not Handsome. Check out a demo of Handsome here: http://handsome.herokuapp.com/

Sorry for the confusion!
