### ISSUE TITLE
With windows 10

### ISSUE THREAD

**Issue by debmalya** [davefp/handsome#22]
today is my first day with handsome. I am trying to run it from windows 10 with command 
handsome-master>docker-compose build
Then got following message
```
Building handsome_ui
Step 1/10 : FROM node:8.7
8.7: Pulling from library/node
ERROR: Service 'handsome_ui' failed to build: no matching manifest for windows/amd64 in the manifest list entries
```
Am I missing any thing?

**Comment by davefp** [comment]
I've not used docker on windows before, but from the looks of things the base node image is not available for Windows containers. You should be able to get docker to use Linux containers instead, but you'll have to look that up yourself as I'm not familiar with the process.

**Comment by debmalya** [comment]
@davefp , Thanks for your comment and looking into this. I will check more .

**Comment by davefp** [comment]
Closing this issue for now, feel free to re-open it if you're still having problems.
